name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Django-Inventory-Management-System
            git pull origin main
            rm -rf venv
            python3 -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install django>=3.2.0,<4.0.0
            pip install django-crispy-forms>=1.14.0
            pip install crispy-bootstrap4>=2022.1
            pip install whitenoise>=6.0.0
            pip install gunicorn>=20.1.0
            python manage.py migrate
            sudo systemctl restart gunicorn 