name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Django-Inventory-Management-System
            git pull origin main
            rm -rf venv
            python3 -m venv venv
            source venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            python manage.py collectstatic --noinput
            python manage.py migrate
            sudo systemctl restart gunicorn 