name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Django-Inventory-Management-System
            git pull origin main
            source venv/bin/activate
            pip install --no-deps Django==3.2.23
            pip install --no-deps django-crispy-forms==1.14.0
            pip install --no-deps crispy-bootstrap4==2022.1
            pip install --no-deps whitenoise==6.0.0
            pip install --no-deps gunicorn==20.1.0
            pip install --no-deps python-decouple==3.8
            python manage.py migrate
            sudo systemctl restart gunicorn 