name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Django-Inventory-Management-System
            git pull origin main
            source venv/bin/activate
            pip uninstall -y urllib3 botocore boto3
            pip install urllib3==1.26.18
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn 